### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by juhoaj** [AaaDee/Regex-Ctrl-F#1]
Ladattu katselmoitavaksi 2.6. 17:50

Projektin määrittely on hyvin selkeä ja antaa vaikutelman että aihealue on hyvin tutkittu. Varsinainen koodi on kirjoitettu hyvin selkeästi. Ohjelman ajon kulkua on helppo seurata vaikka aihealue on koodin lukijalle vieras eikä kommentointi vielä ole Javadoc -formaatissa.

Ohjelman ja dokumentoinnin ollessa kesken on vielä vaikea hahmottaa miten sovelluksen tulisi toimia. Esim. InfixToPostfixParser metodit `formatInput` että `convertInfixToPostfix` metodit palauttavat erilaisia palautuksia kuin [netistä löytyneessä esimerkissä](https://interactivepython.org/runestone/static/pythonds/BasicDS/InfixPrefixandPostfixExpressions.htm). Aihealue on vieras ja tämä saattaa toki olla tarkoituksellista.

Projektissa on vielä verrattain vähän testausta. Tulee mieleen että pääsisikö koodatessa helpommalla mikäli soveltaisi hieman enemmän test-driven lähestymistä? Voisiko esim. `InfixToPostfixParser` kehittäminen helpottua jos lisää reippaasti testejä netistä löytyvillä esimerkki-käännöksillä?

Pääsisikö testauksessa pitkällä tähtäimellä helpommalla jos sijoittaisi testit sovelluksen paketteja vastaaviin paketteihin ja luokkien nimiä vastaaviin testitiedostoihin? Esim. `test/java/regex/InfixToPostfixParserTest.java`?

Kaiken kaikkiaan hyvin selkeän näköistä työtä!

**Comment by AaaDee** [comment]
Hei, kiitoksia kommenteista ja projektin erittäin kattavasta läpikäynnistä!

Tsekkasin tuon Python-esimerkin, ja nopeasti vaikuttaisi siltä, että omassa projektissani pistettä käytetään eksplisiittisenä operaattorina (eli AB on muodossa A.B), mitä linkkaamassasi esimerkissä ei tehdä. Hyvä huomio, laitan tästä maininnan tuleviin javadoceihin, koska asia ei ole täysin standard-meiningillä.

Toi testauksen muuttaminen pakettien mukaan on kyllä fiksu veto, pitää yrittää ehtiä muuttamaan tää ennen loppupalautusta. Oma ajatus oli, että regex-toiminnallisuutta testataan yhdessä luokassa, parseria yhdessä jne, mutta luokkakohtainen jako kuulostaa näin jälkikäteen edelleen fiksummalta ratkaisulta.

TDD on kyllä hyvä tällaisessa projektissa kanssa, huomasin sen nyt kun aloin toteuttamaan varsinaista regexiä, väsääminen oli kyllä paljon helpompaa kun heti huomasi, jos vanhat testit menivät pieleen (:
