### ISSUE TITLE
Katselmointi #1

### ISSUE THREAD

**Issue by lahdeero** [AaaDee/Regex-Ctrl-F#2]
Kiva ui. Perustapaukset tuntu toimivan hyvin eli tiedostosta löytyi haettu merkkijono, | eli tai operaattorin haut onnistui myös hienosti. Erikoisemmissa hauissa tuntui stacktrace pamahtavan ruutuun/Netbeanssiin turhan usein, eli virhetilanteiden kässittelyn totetusta odotellessa. Käyttöohjeissa noi markdownin tähdet oli vähä vaikeesti hahmotettavissa ilman muokkaustyökalua. Javadockia huutais, eli ainakin public metodeihin kaipaisin sitä selkeyttämään. Pelkät satunnaiset kommentit ei hirveesti lämmitä, kun yrittää ymmärtää kokonaiskuvaa. Kuitenkin koodi oli yleisesti hyväksi todettujen käytäntöjen mukaista ja helposti luettavaa.

**Comment by AaaDee** [comment]
Jes kiitoksia kommenteista! Joo, vielä tällä hetkellä stacktrace tulee käytännössä aina kun merkkijonosta ei saa muodostettua nfa:ta, eli vähintäänkin joku try/catch -rakennelma on tulossa. Javadocit tulossa mahdollisimman pian myöskin, kiitoksia kun jaksoit algoritmin kahlata läpi näistä huolimatta! -A
